### PR TITLE
[Feature 51] Delete account

### PR DESCRIPTION
**Pull request by alexxispn**
## Description

Create alert for delete account.

## Changes

- Create Hook with alert for delete account.
- Add text on i18n for the alert.

## Checks

- [X] Project Builds
- [X] Project passes tests and checks
- [x] Updated documentation accordingly

## Additional information
- The logic for the alert has been implemented with a hook, but it has not been integrated with the menu yet. This will be done once the Menu issue is resolved and merged.

Reference: [51] Delete account
URL: https://github.com/TheTributeCommunity/fesbal-frontend/issues/31

### CODE REVIEW

**Review by yodra — APPROVED** [review]
LGTM! 👍

**Comment by rdiaz82** [comment]
hey @alexxispn we have merged all the dependant PRs following your sequence of creation and now we just have to merge this branch into main. 

The problem here, is that as you can see there are a lot of conflicts to merge this branch. I have tried to solve the conflicts by myself but without the full context of the tasks and not 100% sure about what I'm doing. Could you take care of solve the conflicts?

**Comment by alexxispn** [comment]
Hi @rdiaz82! I've already taken care of resolving the conflicts on the merge. I also double-checked everything locally and made sure everything is working as it should be, and also updated some links to follow Figma wireframes. Let me know if there's anything else I need to do before we merge it into the main branch.

**Comment by rdiaz82** [comment]
@alexxispn Thank you so much for solve this task! I'm going to proceed to merge it.

**Pull request merged**
